pull_request_template:
  branches:
    dev: pull_request_template/dev.md
    stage: pull_request_template/stage.md
    prod: pull_request_template/prod.md
    dev:
      template: PULL_REQUEST_TEMPLATE/dev.md
    stage:
      template: PULL_REQUEST_TEMPLATE/stage.md
    production:
      template: PULL_REQUEST_TEMPLATE/production.md
  

