pulls:
  branches:
    dev:
      template: PULL_REQUEST_TEMPLATE/dev.md
    staging:
      template: PULL_REQUEST_TEMPLATE/stage.md
    production:
      template: PULL_REQUEST_TEMPLATE/production.md
  