
---

### **Step 2: GitHub Action Workflow**

Here’s how to extract the values from the PR description dynamically and use them in subsequent steps.

Create a file `.github/workflows/deploy.yaml`:

```yaml
name: Dynamic Deployment

on:
  pull_request:
    types: [opened, edited]

jobs:
  extract-inputs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Extract PR Description Inputs
      id: extract-inputs
      run: |
        echo "Extracting PR inputs..."
        PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
        echo "PR_BODY=$PR_BODY"
        
        # Extract values dynamically (example for DEV-US)
        DEV_US=$(echo "$PR_BODY" | grep "DEV - US:" | awk -F':' '{print $2}' | xargs)
        echo "DEV_US=$DEV_US"

        # Export variables
        echo "DEV_US=$DEV_US" >> $GITHUB_ENV

    - name: Display Extracted Variables
      run: |
        echo "DEV-US Image Tag: $DEV_US"

  deploy:
    needs: extract-inputs
    runs-on: ubuntu-latest

    steps:
    - name: Deploy with Extracted Inputs
      run: |
        echo "Using DEV-US Image Tag: $DEV_US"
        # Add deployment logic here
