name: Update PR Description with Environment Variables

on:
  pull_request:
    types: [opened, edited]

jobs:
  update-pr-description:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Extract environment variable values
        env:
          DEV_VAR_1: ${{ secrets.DEV_VAR_1 }}
          STG_VAR_2: ${{ secrets.STG_VAR_2 }}
          PROD_VAR_3: ${{ secrets.PROD_VAR_3 }}
        run: |
          echo "DEV_VAR_1=${DEV_VAR_1}" >> $GITHUB_ENV
          echo "STG_VAR_2=${STG_VAR_2}" >> $GITHUB_ENV
          echo "PROD_VAR_3=${PROD_VAR_3}" >> $GITHUB_ENV

      - name: Update PR Description
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Description
            Please describe the changes in this PR.

            ## Environment Tags
            | Environment | Variable | Value |
            |-------------|----------|-------|
            | DEV         | VAR_1    | ${{ env.DEV_VAR_1 }} |
            | STG         | VAR_2    | ${{ env.STG_VAR_2 }} |
            | PROD        | VAR_3    | ${{ env.PROD_VAR_3 }} |

           